name: Unit tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global url."https://${{ secrets.TOKEN_GITHUB }}@github.com/".insteadOf ssh://git@github.com/
      - run: npm install
      - run: npm run link
      - run: npm run bootstrap
      - run: npm run lint
      - run: npm run test
      # - run: npm run coverage
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{secrets.coveralls_repo_token}}
      #     CONTINUOUS_INTEGRATION: true
